# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eh2Fz1grU73Kx4MQ896KBbN-yXD0-Bsc
"""

import streamlit as st
from rdkit import Chem
from rdkit.Chem import Descriptors, Draw
from PIL import Image
import io

# App Layout
st.set_page_config(page_title="NDSRI Consensus Screener PoC", layout="wide")
st.title("🧪 NDSRI In Silico Consensus Screener (Proof of Concept)")
st.markdown("Developed by David Mekhael - University of Gdańsk")

# User Input
smiles_input = st.text_input("Enter SMILES String:", "")

if smiles_input:
    mol = Chem.MolFromSmiles(smiles_input)

    if mol:
        st.success("Molecule successfully parsed!")

        col1, col2 = st.columns(2)

        with col1:
            st.subheader("2D Structure")
            img = Draw.MolToImage(mol, size=(400, 400))
            st.image(img)

        with col2:
            st.subheader("RDKit Molecular Descriptors")
            st.write(f"**Molecular Weight:** {Descriptors.MolWt(mol):.2f} g/mol")
            st.write(f"**LogP (Lipophilicity):** {Descriptors.MolLogP(mol):.2f}")
            st.write(f"**TPSA (Polar Surface Area):** {Descriptors.TPSA(mol):.2f} Å²")
            st.write(f"**Hydrogen Bond Donors:** {Descriptors.NumHDonors(mol)}")
            st.write(f"**Hydrogen Bond Acceptors:** {Descriptors.NumHAcceptors(mol)}")

        st.divider()
        
        # --- THE UPGRADED "SMART" PIPELINE ---
        st.subheader("🤖 Consensus ML Pipeline (Structural Alert)")
        st.info("In the full PhD project, this section will feature a Scikit-learn Random Forest classifier. For this PoC, it utilizes RDKit SMARTS matching to detect toxicophores.")
        
        # Define the Nitrosamine pattern (N-N=O) using SMARTS
        nitrosamine_pattern = Chem.MolFromSmarts('N-N=O')
        
        # Check if the molecule contains the pattern
        if mol.HasSubstructMatch(nitrosamine_pattern):
            st.error("🚨 **TOXICOPHORE DETECTED:** Nitrosamine (N-N=O) group found! High risk of mutagenicity. Flagged for Ames MPF testing.")
        else:
            st.success("✅ **CLEARED:** No Nitrosamine toxicophore detected in this structure.")
    else:
        st.error("Invalid SMILES string. Please try again.")
