# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eh2Fz1grU73Kx4MQ896KBbN-yXD0-Bsc
"""

import sys
!{sys.executable} -m pip install streamlit
!{sys.executable} -m pip install rdkit
import streamlit as st
from rdkit import Chem
from rdkit.Chem import Descriptors, Draw
from PIL import Image
import io

# App Layout
st.set_page_config(page_title="NDSRI Consensus Screener PoC", layout="wide")
st.title("🧪 NDSRI In Silico Consensus Screener (Proof of Concept)")
st.markdown("Developed by David Mekhael - University of Gdańsk")

# User Input
smiles_input = st.text_input("Enter SMILES String:", "O=NN(C)CCC(c1ccccc1)Oc2ccc(cc2)C(F)(F)F") # Default is N-nitroso-fluoxetine

if smiles_input:
    mol = Chem.MolFromSmiles(smiles_input)

    if mol:
        st.success("Molecule successfully parsed!")

        col1, col2 = st.columns(2)

        with col1:
            st.subheader("2D Structure")
            img = Draw.MolToImage(mol, size=(400, 400))
            st.image(img)

        with col2:
            st.subheader("RDKit Molecular Descriptors")
            st.write(f"**Molecular Weight:** {Descriptors.MolWt(mol):.2f} g/mol")
            st.write(f"**LogP (Lipophilicity):** {Descriptors.MolLogP(mol):.2f}")
            st.write(f"**TPSA (Polar Surface Area):** {Descriptors.TPSA(mol):.2f} Å²")
            st.write(f"**Hydrogen Bond Donors:** {Descriptors.NumHDonors(mol)}")
            st.write(f"**Hydrogen Bond Acceptors:** {Descriptors.NumHAcceptors(mol)}")

        st.divider()

        # Placeholder for the ML Pipeline you proposed
        st.subheader("🤖 Consensus ML Pipeline (Simulated)")
        st.info("In the full PhD project, these features will be fed into a Scikit-learn Random Forest classifier trained on ToxRefDB to output a final toxicity score.")
        st.warning("Simulated Prediction: **High Reactivity Alert (N-N=O group detected)**")

    else:
        st.error("Invalid SMILES string. Please try again.")